[package]
categories   = ["asynchronous"]
description  = "Asynchronous Language Server Protocol (LSP) framework based on tower"
edition      = "2021"
include      = ["/Cargo.toml", "/LICENSE-APACHE", "/LICENSE-MIT", "/README.md", "/benches", "/examples", "/src", "/tests"]
keywords     = ["language-server", "lsp", "tower"]
license      = "MIT OR Apache-2.0"
name         = "async-lsp"
repository   = "https://github.com/oxalica/async-lsp"
rust-version = "1.88.0"
version      = "0.2.2"

[features]
client-monitor = ["dep:rustix", "dep:waitpid-any"]
default        = ["client-monitor", "omni-trait", "stdio", "tracing"]
forward        = []
omni-trait     = []
stdio          = ["dep:rustix", "rustix?/fs", "tokio?/net"]
tracing        = ["dep:tracing"]

[[example]]
name              = "client_builder"
required-features = ["omni-trait", "tokio", "tracing"]

[[example]]
name              = "client_trait"
required-features = ["omni-trait", "tokio", "tracing"]

[[example]]
name              = "server_builder"
required-features = ["client-monitor", "omni-trait", "stdio", "tokio", "tracing"]

[[example]]
name              = "server_trait"
required-features = ["client-monitor", "omni-trait", "stdio", "tokio", "tracing"]

[[example]]
name              = "inspector"
required-features = ["forward", "tokio", "tracing"]

[[test]]
name              = "unit_test"
required-features = ["omni-trait", "tokio"]

[[test]]
harness           = false
name              = "stdio"
required-features = ["stdio", "tokio"]

[[bench]]
harness = false
name    = "bench"

[dependencies]
async-io                     = { workspace = true, optional = true }
futures.workspace            = true
lsp-types.workspace          = true
pin-project-lite             = "0.2.16"
rustix                       = { workspace = true, optional = true }
serde.workspace              = true
serde_json.workspace         = true
thiserror                    = "2"
tokio                        = { workspace = true, optional = true }
tower-layer.workspace        = true
tower-service.workspace      = true
tracing                      = { workspace = true, optional = true }
tracing-subscriber.workspace = true
waitpid-any                  = { workspace = true, optional = true }


[dev-dependencies]
async-io      = { version = "2.4.0" }
async-process = "2.3.0"
# Workaround: https://github.com/bheisler/criterion.rs/issues/702
clap               = { version = "4.5.37", features = ["cargo", "env", "string", "wrap_help"] }
criterion          = { version = "0.5.1", features = ["async_tokio"] }
tokio              = { version = "1.45.0", features = ["full", "io-std", "io-util", "macros", "process", "rt", "time", "tracing"] }
tokio-util         = { version = "0.7.15", features = ["compat"] }
tower              = "0.5.2"
tracing-subscriber = { version = "0.3.19", features = ["chrono", "fmt", "local-time"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
