style_edition = "2024"
edition = "2024"
use_small_heuristics = "Default"
max_width = 120
hard_tabs = false
tab_spaces = 4
wrap_comments = true
format_code_in_doc_comments = false
doc_comment_code_block_width = 120
comment_width = 120
normalize_comments = true
normalize_doc_attributes = true
